### PR TITLE
tab select bug

### PR DESCRIPTION
**Pull request by joaoafrmartins**

### CODE REVIEW

**Comment by rpocklin** [comment]
Hi, thanks for the PR.

What issue are you fixing here?

I also noticed you added `./` to the `main` section in `bower.json` - did it not work without it?

**Comment by joaoafrmartins** [comment]
hey there! I was having some trouble when selecting the tab from an href...

navbar | cat v
                 tab1
                 tab2

tab1 | tab2

navbar tab1 click > tab1 active ok > tab2 click > tab2 active ok > navbar tab1 click > tab1 active fail

**Comment by rpocklin** [comment]
Hi,

Do you see this problem in the online demo?  If not, send me a plunkr and i'll take a look.  As it is the PR you submitted fails the build.

**Comment by rpocklin** [comment]
Closing due to inactivity.

**Pull request closed without merging**
