### PR TITLE
why not allow a standard ui-view in the tab-pane?

### PR DESCRIPTION
**Pull request by mareczek**
I don't want to do anything fancy, just display a standard tab-pane with a ui-view

### CODE REVIEW

**Comment by rpocklin** [comment]
I've had a lot of requests for this, so i'll make this happen either in the default template or an another way.

**Comment by mareczek** [comment]
will do, but first I'll have to think of a way to force uib-tabset not to create the tab-content node. With this solution, the ui-view should be present only once

**Comment by rpocklin** [comment]
Yes i've encountered the same issue.  Seems to happen upstream (from ui-bootstrap) not sure if it's possible to change or maybe this directive should remove it explicitly.

**Comment by rpocklin** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
