### PR TITLE
Add CommonJS package manager support (closes #43)

### LINKED ISSUE #43: Add commonjs package manager support
Can we add support for loading uiRouterTabs as a CommonJS module?

See example of Angular UI-Router:
https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js

This will allow doing:
```js
var uiRouterTabs = require('angular-ui-router-tabs');

angular.module('admin', [
    uiRouterTabs
])
```

Instead of hard coding the module name.

### PR DESCRIPTION
**Pull request by alexilyaev**

### CODE REVIEW

**Comment by rpocklin** [comment]
I'm hesitant to leave the build in a broken state - any way you can get this to work?
Also will this break anything for non-webpack scenarios?

**Comment by alexilyaev** [comment]
I've fixed the broken build, was missing global variables `module` and `exports` in `.jshintrc`.
But now it says something about the Coverage decreased, I'm not sure how to cover that, since it's not inside the module.

Environments that don't use CommonJS will not enter the `if` with the `module.exports`, and for those who do support it, it's only a convenience, people can still use the old way.

**Comment by alexilyaev** [comment]
@rpocklin Can we bump a release for this one?

**Comment by rpocklin** [comment]
Done! `v1.6.0` - thanks for bumping me.

**Comment by alexilyaev** [comment]
Did you `npm publish`?
How does that work anyway? I mean how does a release tag get on the npm repository?

**Comment by rpocklin** [comment]
I wish it was automatic :P  it's published now.

**Pull request merged**
