### PR TITLE
Added 'bower install' as npm post-install script.

### PR DESCRIPTION
**Pull request by amahfouz**
Add an optional configuration parameter "tab-classes" to allow configuring the tabs with arbitrary classes, such as "btn-sm", etc.

### CODE REVIEW

**Comment by rpocklin** [comment]
What's wrong with just passing `class` instead of `tab-classes`?

**Comment by rpocklin** [comment]
If you can re-work this i'll accept it.

**Comment by amahfouz** [comment]
Thanks. Will do. I am currently trying to get a pull request into the
angular-bootstrap so that my change here makes it all the way through.

**Comment by rpocklin** [comment]
Made similar changes to `master` branch, feel free to give feedback on it.

**Pull request closed without merging**
