### PR TITLE
Switch tabs iif tab state is inactive, closes #10

### LINKED ISSUE #10: Clicking active tab makes tab inactive
As per #7, I think this is unexpected behaviour as it differs to [ui-bootstrap](https://angular-ui.github.io/bootstrap/#/tabs)'s behaviour; in ui-bootstrap, you cannot click a tab that's already active.

This happens because ui-bootstrap's behaviour is effectively overridden via the use of `ui-sref`.

### PR DESCRIPTION
**Pull request by tlvince**

### CODE REVIEW

**Comment by rpocklin** [comment]
Thanks for the PR.  It's a good attempt, but if I open the example and click `Settings` it works the first time, but I then re-click `Settings` and it performs the original behaviour.  Might need more work.

If I have a chance in the next few days i'll go over the code but feel free to amend the PR.

**Comment by tlvince** [comment]
Hmm, strange. I can't reproduce this. Are you loading `ui-router-tabs.js` from my fork?

**Comment by rpocklin** [comment]
Sorry, I checked out your `master` not `bug/active-inactive` - let me take a closer look :)

**Comment by tlvince** [comment]
Sorry, I'm pretty tied up right now, but agreed, it could probably use a test.

NB, if you merge this, could you release a new tag?

**Comment by rpocklin** [comment]
I've added an assertion to a test which failed before this commit was added, so that's been covered off now.  Released `1.2.0`.

**Comment by tlvince** [comment]
Great, thanks! :+1:

**Pull request merged**
